### ISSUE TITLE
 scale by the standard deviations part is wrong??

### ISSUE THREAD

**Issue by cvley** [jrosebr1/color_transfer#1]
hi, I have tried your code, but seems a bit wrong here =>
  color_transfer / color_transfer / **init**.py

in the 42~45 lines, 
# scale by the standard deviations

```
l = (lStdTar / lStdSrc) * l
a = (aStdTar / aStdSrc) * a
b = (bStdTar / bStdSrc) * b
```

the StdSrc and StdTar should be replaced with each other.

I will try more test images and feedback to you~

**Comment by jrosebr1** [comment]
Hi,

Thanks for reaching out!

Take a look at the original Color Transfer between Images
http://www.thegooch.org/Publications/PDFs/ColorTransfer.pdf paper by
Reinhard et al., specifically page 3, equation 11.

Notice how the target standard deviation for each channel is divided by the
source standard deviation. This implementation of the color transfer
algorithm follows the Reinhard suggestion; however, if you like the results
better by switching the standard deviations, feel free to do so!

I hope that helps,

-Adrian

**Comment by cvley** [comment]
@jrosebr1 
thanks, I will check out the paper~
