### ISSUE TITLE
Issue with images

### ISSUE THREAD

**Issue by Daguerreo** [jrosebr1/color_transfer#2]
Line 26
target = cv2.cvtColor(target, cv2.COLOR_BGR2LAB).astype("float32")

while trying to use differents jpg, raise error during the conversion to float32:

 target = cv2.cvtColor(target, cv2.COLOR_BGR2LAB).astype("float32")
cv2.error: ........\opencv\modules\imgproc\src\color.cpp:4118: error: (-215) (scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F) in function cv::cvtColor

**Comment by jrosebr1** [comment]
It sounds like `target` (and also very likely `source`) were not properly loaded from disk. Double check your paths to these images when you specify them via command line argument. Again, I am almost 100% confident this error is due to invalid paths to images being supplied.

**Comment by Daguerreo** [comment]
You were right, sorry for the issue

**Comment by jrosebr1** [comment]
No worries, glad it's resolved :-)
